# --- Production profile for Spendwise ---
spring:
  config:
    activate:
      on-profile: production

  datasource:
    url: ${JDBC_DATABASE_URL:jdbc:postgresql://dpg-d3prvt63jp1c7386ojh0-a.oregon-postgres.render.com:5432/spendwise_prod_db}
    username: ${DB_USER:spendwise_prod_db_user}
    password: ${DB_PASSWORD:ICS0fTDuaGSpuxTMjRtBCIzpdaXswBNn}
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 10
      minimum-idle: 5
      connection-timeout: 30000
      idle-timeout: 600000
      max-lifetime: 1800000

  jpa:
    hibernate:
      ddl-auto: validate  # Don't auto-create in production
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: false
        default_schema: spendwise

logging:
  level:
    root: INFO
    com.tushar.spendwise: INFO
    org.springframework.web: WARN
    org.springframework.security: WARN
    org.hibernate: WARN
