# --- Production profile for SpendWise ---
spring:
  config:
    activate:
      on-profile: production

  datasource:
    # Use DATABASE_URL if available (Render style)
    url: ${JDBC_DATABASE_URL:jdbc:postgresql://dpg-d3prvt63jp1c7386ojh0-a.oregon-postgres.render.com:5432/spendwise_prod_db}
    username: ${DB_USERNAME:spendwise_prod_db_user}
    password: ${DB_PASSWORD:ICS0fTDuaGSpuxTMjRtBCIzpdaXswBNn}
    driver-class-name: org.postgresql.Driver

    hikari:
      maximum-pool-size: 10
      minimum-idle: 5
      connection-timeout: 30000
      idle-timeout: 600000
      max-lifetime: 1800000
      pool-name: SpendwiseHikariPool

  jpa:
    hibernate:
      ddl-auto: validate   # Safe for production — validates schema, doesn't recreate
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: false
        default_schema: spendwise
        jdbc.lob.non_contextual_creation: true
        temp.use_jdbc_metadata_defaults: false

  sql:
    init:
      mode: never   # Don't auto-run SQL scripts in production

server:
  port: ${PORT:8080}

logging:
  level:
    root: INFO
    com.tushar.spendwise: INFO
    org.springframework.web: WARN
    org.springframework.security: WARN
    org.hibernate: WARN
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
