spring:
  config:
    activate:
      on-profile: prod

  # PostgreSQL Database Configuration for Production
  datasource:
    url: jdbc:postgresql://dpg-d3l749j3fgac73abrvo0-a.oregon-postgres.render.com:5432/geotrackr
    username: geotrackr_user
    password: 4ldgg77xYGpOl3PNbJxPQxqjaTUrJ6Je
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 10
      minimum-idle: 5
      connection-timeout: 30000
      idle-timeout: 600000
      max-lifetime: 1800000

  jpa:
    show-sql: false
    hibernate:
      ddl-auto: validate  # Don't auto-create in production
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: false
        default_schema: spendwise

# Server Configuration
server:
  port: ${PORT:8080}
  error:
    include-message: never
    include-binding-errors: never
    include-stacktrace: never
  compression:
    enabled: true
    mime-types: text/html,text/xml,text/plain,text/css,text/javascript,application/javascript,application/json
    min-response-size: 1024

# Logging Configuration
logging:
  level:
    com.finance.aiexpense: INFO
    org.springframework.security: WARN
    org.springframework.web: WARN
    org.hibernate: WARN
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
  file:
    name: logs/application.log
    max-size: 10MB
    max-history: 30